/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ExperimentsContract2,
  ExperimentsContract2Interface,
} from "../ExperimentsContract2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "isTrue",
        type: "bool",
      },
    ],
    name: "sequentialAccessA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610244806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806352090bb914610030575b600080fd5b61004a60048036038101906100459190610108565b610060565b6040516100579190610187565b60405180910390f35b6000816100a2576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161009990610167565b60405180910390fd5b6000600160a3510151600260a3510151600360a3510151600460a3510151600560a3510151818581019050848101905083810190508281019050818101905080965050505050505080915050919050565b600081359050610102816101f7565b92915050565b60006020828403121561011e5761011d6101c9565b5b600061012c848285016100f3565b91505092915050565b60006101426015836101a2565b915061014d826101ce565b602082019050919050565b610161816101bf565b82525050565b6000602082019050818103600083015261018081610135565b9050919050565b600060208201905061019c6000830184610158565b92915050565b600082825260208201905092915050565b60008115159050919050565b6000819050919050565b600080fd5b7f7265715f73657175656e7469616c416363657373410000000000000000000000600082015250565b610200816101b3565b811461020b57600080fd5b5056fea2646970667358221220fe51dbf07d62aeba9aa43db765532494fe1981259655af888f1dfafbbc2da32c64736f6c63430008070033";

export class ExperimentsContract2__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExperimentsContract2> {
    return super.deploy(overrides || {}) as Promise<ExperimentsContract2>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExperimentsContract2 {
    return super.attach(address) as ExperimentsContract2;
  }
  connect(signer: Signer): ExperimentsContract2__factory {
    return super.connect(signer) as ExperimentsContract2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExperimentsContract2Interface {
    return new utils.Interface(_abi) as ExperimentsContract2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExperimentsContract2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ExperimentsContract2;
  }
}
