/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ExperimentsContract2,
  ExperimentsContract2Interface,
} from "../ExperimentsContract2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "isTrue",
        type: "bool",
      },
    ],
    name: "sequentialAccessA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a8806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806352090bb914610030575b600080fd5b61004a6004803603810190610045919061016c565b610060565b60405161005791906101eb565b60405180910390f35b6000816100a2576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610099906101cb565b60405180910390fd5b60006100e3565b600060a3905090565b600060b351805191506001810160b5525090565b600060c3516100d36100a9565b81510191506001810160c5525090565b6100eb6100a9565b60a6016100f66100b2565b6100fe6100c6565b6101066100a9565b8101820183016101146100a9565b8160005b6101008110156101445761012a6100c6565b8201915060d3820191508282019150602081019050610118565b5080965050505050505080915050919050565b6000813590506101668161025b565b92915050565b6000602082840312156101825761018161022d565b5b600061019084828501610157565b91505092915050565b60006101a6601583610206565b91506101b182610232565b602082019050919050565b6101c581610223565b82525050565b600060208201905081810360008301526101e481610199565b9050919050565b600060208201905061020060008301846101bc565b92915050565b600082825260208201905092915050565b60008115159050919050565b6000819050919050565b600080fd5b7f7265715f73657175656e7469616c416363657373410000000000000000000000600082015250565b61026481610217565b811461026f57600080fd5b5056fea264697066735822122011d1290fa4ad7837bf0344a397b34b860469ef175c8c72e05f90833d78c0730964736f6c63430008070033";

export class ExperimentsContract2__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExperimentsContract2> {
    return super.deploy(overrides || {}) as Promise<ExperimentsContract2>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExperimentsContract2 {
    return super.attach(address) as ExperimentsContract2;
  }
  connect(signer: Signer): ExperimentsContract2__factory {
    return super.connect(signer) as ExperimentsContract2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExperimentsContract2Interface {
    return new utils.Interface(_abi) as ExperimentsContract2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExperimentsContract2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ExperimentsContract2;
  }
}
