/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ExperimentsContract2,
  ExperimentsContract2Interface,
} from "../ExperimentsContract2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "isTrue",
        type: "bool",
      },
    ],
    name: "sequentialAccessA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061038c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806352090bb914610030575b600080fd5b61004361003e36600461032d565b610055565b60405190815260200160405180910390f35b6000816100a05760405162461bcd60e51b81526020600482015260156024820152747265715f73657175656e7469616c4163636573734160581b604482015260640160405180910390fd5b600060405160108101516011820151601283015160138401516014850151601586015160168701516017880151601889015160198a015160a08b0151995060a18b0151985060a28b0151975060a38b0151965060a48b0151955060a58b0151945060a68b0151935060a78b0151925060a88b0151915060a98b0151905060b08b01518a01995060b18b01518901985060b28b01518801975060b38b01518701965060b48b01518601955060b58b01518501945060b68b01518401935060b78b01518301925060b88b01518201915060b98b01518101905060c08a01995060c18901985060c28801975060c38701965060c48601955060c58501945060c68401935060c78301925060c88201915060c98101905060f060e08c01510160d08c015260f160e18c01510160d18c015260f260e28c01510160d28c015260f360e38c01510160d38c015260f460e48c01510160d48c015260f560e58c01510160d58c015260f660e68c01510160d68c015260f760e78c01510160d78c015260f860e88c01510160d88c015260f960e98c01510160d98c015261ff008b0161ff00810160f08d015160e08301510160d082015260f18d015160e18301510160d182015260f28d015160e28301510160d282015260f38d015160e38301510160d382015260f48d015160e48301510160d482015260f58d015160e58301510160d582015260f68d015160e68301510160d682015260f78d015160e78301510160d782015260f88d015160e88301510160d882015260f98d015160e98301510160d98201525050869a50898b019a50888b019a50878b019a50868b019a50858b019a50848b019a50838b019a50828b019a50818b019a50808b019a50505050505050505050508091505080915050919050565b60006020828403121561033f57600080fd5b8135801515811461034f57600080fd5b939250505056fea2646970667358221220bcfb20f4200eddd8de895dc4ca03f01c27755f09e1b2261f26c69394bc83d23164736f6c63430008070033";

export class ExperimentsContract2__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExperimentsContract2> {
    return super.deploy(overrides || {}) as Promise<ExperimentsContract2>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExperimentsContract2 {
    return super.attach(address) as ExperimentsContract2;
  }
  connect(signer: Signer): ExperimentsContract2__factory {
    return super.connect(signer) as ExperimentsContract2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExperimentsContract2Interface {
    return new utils.Interface(_abi) as ExperimentsContract2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExperimentsContract2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ExperimentsContract2;
  }
}
